name: Lint Markdown
on:
  pull_request:
    paths: ["**/*.md"]
  push:
    branches: ["main"]
jobs:
  mdlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: "**/*.md"
